### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by alexvoss** [simoninireland/epyc#1]
Hi Simon,

am playing around with epyc and one thing I stumbled across is line 173 in epyc/experiment.py, which needs parentheses added around the string to be printed to be compatible with Python3. Are you aiming for epyc to be Python 3 compatible? If not then please add a note to the installation instructions.

Cheers, Alex

**Comment by simoninireland** [comment]
Hi Alex,

Now fixed for Python3 compatibility, and I'm about to do the JoSS submission too. Further use and comments welcome :-).

Cheers,

-- Simon
