### ISSUE TITLE
JOSS-paper DOIs

### ISSUE THREAD

**Issue by zbeekman** [simoninireland/epyc#11]
Hi, it looks like you have a DOI for *Design of comparative experiments* but perhaps the ISBN should be removed to display that instead? [I tried told @whedon to regenerate the draft PDF](https://github.com/openjournals/joss-reviews/issues/3764#issuecomment-962192322) but the generated document still shows the ISBN. Maybe I should ask the JOSS editors if one is preferred over the other.

Also, my initial searching seems to indicate that there is no DOI available for *Epidemic modelling -- some notes, maths and code.* and likewise there is no DOI for the Software Sustainability Institute *Guides for researchers*. Is this correct? Have you searched for DOIs for these items?

**Comment by zbeekman** [comment]
It looks like pandoc/the document compilation system is not correctly recognizing your DOIs (https://github.com/openjournals/joss-reviews/issues/3764#issuecomment-962197918). I'm not sure whether this is due to the capitalization of the DOI url in the bibtex `url` field, or if you need to use a different field in the bibtex style bibliography to make it recognize the doi.

It looks like maybe you need to be using the bibtex `doi` field instead of `url`: https://www.bibtex.com/f/doi-field/

**Comment by zbeekman** [comment]
(Also, [the editor confirmed](https://www.bibtex.com/f/doi-field/) DOIs are preferred over ISBN etc. Perhaps changing the bibtex entries to use the `doi` field will resolve this issue of the isbn being preferred over the doi?)

**Comment by zbeekman** [comment]
> please update the bib file to store dois in doi = {} fields, not url fields. these should be of the form doi = {a.b/...} without the full URL listing

I'll submit a PR in a bit if I have time

**Comment by simoninireland** [comment]
Updated to DOI fields. The bibtex style seems to prefer ISBNs to DOIs, so I removed the ISBN from "Design of comparative experiments". 

There is no DOI for "Epidemic modelling" (I know because I wrote it :-)), and none for the SSI's "Guide for researchers" as it's purely online as a web page.
