### ISSUE TITLE
JOSS-paper unclosed parenthetical element

### ISSUE THREAD

**Issue by zbeekman** [simoninireland/epyc#12]
There is an unclosed parenthetical element in the text [here](https://github.com/simoninireland/epyc/blob/136456558e1d48d62d68df43312fcfc739120915/paper.md?plain=1#L120) at the end of the "Differences with other tools" section. I would submit a PR to fix it but it's not immediately clear to me where the parenthetical clause should end.

**Comment by simoninireland** [comment]
Fixed
