### ISSUE TITLE
[JOSS] Manuscript Review

### ISSUE THREAD

**Issue by amritagos** [simoninireland/epyc#14]
Part of [openjournals/joss-reviews#3764](https://github.com/openjournals/joss-reviews/issues/3764)

The manuscript is succinct, well-written and easy to understand. However, it would be good if the author could provide references for the other workflow managers mentioned in the section on _Differences with other tools_, such as [Snakemake](https://snakemake.readthedocs.io/en/stable/) or [Sacred](https://sacred.readthedocs.io/en/stable/quickstart.html).

**Comment by simoninireland** [comment]
I've added comments on both these tools. Sacred is a new one to me, and is probably the closest thing I've see in spirit to epyc -- thanks.
