### ISSUE TITLE
Possible typo in epyc/jsonlabnotebook.py

### ISSUE THREAD

**Issue by zelenkastiot** [simoninireland/epyc#5]
Hello @simoninireland, 

Recently I came across the jupyter book you posted on introduction to epidemics (very cool!). 

I tried running some of the code locally (I tried running the notebook about epidemic threshold) and I couldn't get it to work. Constantly I got an error in this file: 

https://github.com/simoninireland/epyc/blob/8fa1b398c602f088e8d6e726e97c46e96d9ae562/epyc/jsonlabnotebook.py#L146

After I changed it to <code>['results']</code> and saved it, the error was gone. 
 
My system specs are: 
- Windows 10 
- Python 3.6.9
- epyc=1.3.2
- epydemic=1.3.1 
- networkx=2.5

**Comment by simoninireland** [comment]
Hi Kiril,

Glad you're finding epydemic useful :-).

Thanks for pointing that out. I've not been properly maintaining the JSON notebook format, and clearly I should do a better job with it :-). The HDF5 notebooks are more useful and scalable, I think.

Cheers,

--
-- Simon
