### ISSUE TITLE
JOSS-review

### ISSUE THREAD

**Issue by zbeekman** [simoninireland/epyc#6]
Hi @simoninireland! It seems like the JOSS paper is still in the pre-review/finding reviewers phase, however I have been assigned as a reviewer and thought I'd start the ball rolling so that your JOSS article might get published in a timely fashion and so that I can complete my portion of the review in a timely fashion.

So far things look great, but I'll be opening issues and/or pull requests here in the EPYC repository with items that I feel need addressing and/or discussing along with any improvements I can think of that are pertinent to the review.

The first issue I noticed is that there don't appear to be  very clear ["community guidelines"](https://joss.readthedocs.io/en/latest/review_checklist.html#documentation) as required in the JOSS reviewer checklist for documentation. If I am missing them somewhere on readthedocs or in the repository please let me know. Otherwise I'd recommend adding at least something like a `CONTRIBUTING.(md|org|rst)` file to the root of the Github repository. A code of conduct can also be helpful, and GitHub provides some boilerplates if you go to the "insights" tab towards the top of the repository page and then the "community" menu on the left. (Here: https://joss.readthedocs.io/en/latest/review_checklist.html#documentation)

Other than this, it looks like I can check off a lot of the [reviewer checklist items](https://joss.readthedocs.io/en/latest/review_checklist.html)--at least the ones I've looked at so far!

**Comment by simoninireland** [comment]
Hi @zbeekman. Thanks for starting things :-)

You're right about no contributor guidelines; I'll add some.

The "suggested reviewers" link seems to be broke, BTW.
