### ISSUE TITLE
The `epyc` console script does not work

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [simoninireland/epyc#7]
Hi @simoninireland ,

This is an issue created as part of [epyc's JOSS review](https://github.com/openjournals/joss-reviews/issues/3764).

I have noticed that the setup procedure installs the `epyc` console script. However, the script fails with `ModuleNotFoundError: No module named 'epyc.scripts'`. I have tested both PyPi and github versions.

**Comment by simoninireland** [comment]
Always helps if you include the module in setup.py...:-)
