### ISSUE TITLE
Recommend to use pip rather setup.py

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [simoninireland/epyc#8]
This is an issue created as part of [epyc's JOSS review](https://github.com/openjournals/joss-reviews/issues/3764).

This is a rather minor (and maybe even opinion-based) point, but I think that you should recommend using `pip` to install the package even when cloned from github. 
The main advantage of `pip` over `setup.py` (at least on a linux box) is that the former installs the package in the user home folder by default, whereas the latter gives out an error if the user doesn't have the privileges to install the package in a system folder.

**Comment by simoninireland** [comment]
Do you mean moving to setup.cfg rather than setup.py? I've been wondering about that, but never got round to looking in detail. I'll have another look.

**Comment by lorenzo-rovigatti** [comment]
No, it's a much simpler thing. As of now you recommend installing the package with `python setup.py install`, whereas I think it's simpler to do `pip install .`, so that the package is always managed by pip. As I wrote, it's a very minor thing.

**Comment by simoninireland** [comment]
Ah, OK, didn't know you could do that :-). Fixed.
