### ISSUE TITLE
Testing the installation

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [simoninireland/epyc#9]
This is an issue created as part of [epyc's JOSS review](https://github.com/openjournals/joss-reviews/issues/3764).

I see that the repo has a CI workflow active. However, I don't see any way of triggering the testing suite manually so that I can check whether installation was successful. Can you include the required steps to run the tests in the README and/or in the full documentation?

**Comment by simoninireland** [comment]
The test suite isn't part of the package (as is normally the case, I believe), so it isn't installed when you install the package. You can of course run tests if you have a repo checked out: make test will do that.

**Comment by lorenzo-rovigatti** [comment]
OK thanks. I have tried using `make test` but it fails with the following error (ubuntu 20.04):

```
cat setup.py.in | sed -e 's|VERSION|1.5.1|g' -e 's|REQUIREMENTS|"numpy >= 1.17.5", "pyzmq", "ipyparallel >= 6.2.4", "cloudpickle", "pandas", "h5py", "joblib", "requests", "click", |g' >setup.py
. venv3/bin/activate && tox
/bin/sh: 1: .: Can't open venv3/bin/activate
make: *** [Makefile:203: test] Errore 127
```

**Comment by ajstewartlang** [comment]
@simoninireland do you have any thoughts re. why that error highlighted by @lorenzo-rovigatti occurs? Is there another way to test whether installation is successful?

**Comment by simoninireland** [comment]
That's the venv not having been built, which is weird if done from scratch as env is a dependency of test. Running "make reallyclean && make test" should fix whatever's happening.

**Comment by ajstewartlang** [comment]
@lorenzo-rovigatti can you try @simoninireland's suggestion and see how it goes?

**Comment by lorenzo-rovigatti** [comment]
Yup, that seems to work. Maybe you could add that line somewhere in the docs? Either way, I think we are good to go!

**Comment by simoninireland** [comment]
Added to the contributing/ page on ReadTheDocs.
